custom:
  data: 10002

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
      preferIpAddress:  true
      instance-id:      ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      # 详细信息显示给所有用户。
      show-details: always